num=int(input("ENTER NUMBER FOR WITCH YOU WANT TO FIBONACCI SERIES : "))
i,j=1,1
while(i<=num):
    if(i<=num):
        print(i, end=",")
    if(j<=num):
        print(j, end=" ,")
    i+=j
    j+=i
